### ISSUE TITLE
Empty review submission

### ISSUE THREAD

**Issue by shadowgirl547** [jovojynn/qa-term-project#13]
### **Name**
Empty review submission

### **Status**
Assigned

### **Description**
When a user is in the review section of the Stanley Park page and submits an empty review, a blank review card is added to the existing reviews.

### **Steps to Reproduce**

1. In the address bar, input https://wanderlust.maijomade.com/public/location.php
2. Scroll down to the bottom of the page where the review submission card is
3. Leave all of the fields blank and click the "Submit" button

### **Expected Result**
When the user submits a blank review, they should be given an error stating that they need to fill in the required fields before they can submit a review.

### **Actual Result**
When the user submits a blank review, the review is still processed and it appears with the other existing reviews as a blank card.

![image](https://user-images.githubusercontent.com/116108227/205518431-e9086e4a-3db6-4b7d-ac63-06a66bc5e949.png)

### **Configuration**
This bug was found on the following configurations labeled in red

![image](https://user-images.githubusercontent.com/116108227/205518620-77e45bac-3cc3-4e39-a283-54e050b40e7d.png)

The issue appears on all browsers.

### **Severity**
High

### **Priority**
High

### **Type**
Bug

### **Assignee**
Jovolynn

**Comment by jovojynn** [comment]
I deleted all the extra reviews! Now you have to enter the fields and they can't be empty.
