### ISSUE TITLE
Search results heading text and cards too close together

### ISSUE THREAD

**Issue by shadowgirl547** [jovojynn/qa-term-project#14]
### **Name**
Search results header text and cards too close together

### **Status**
Assigned

### **Description**
When a user searches for a location in the search bar, the cards are positioned directly underneath the heading text.

### **Steps to Reproduce**

1. In the address bar, input https://wanderlust.maijomade.com/public/index.php
2. On the home page, input "b" in the search bar, then click the search icon

### **Expected Result**
When the user searches for a location in the search bar, the cards are positioned underneath the heading text with a generous amount of spacing in between them.

![orig](https://user-images.githubusercontent.com/116108227/205520020-fc59bb3a-c50a-4899-b9af-35546d06689b.PNG)

### **Actual Result**
When the user searches for a location in the search bar, the cards are positioned directly underneath the heading text with no spacing at all.

![bug](https://user-images.githubusercontent.com/116108227/205520039-cd44a1be-5190-427c-ae76-ca9c023cf668.PNG)

### **Configuration**
This bug was found on the following configurations labeled in red

![image](https://user-images.githubusercontent.com/116108227/205518620-77e45bac-3cc3-4e39-a283-54e050b40e7d.png)

The issue appears on all browsers.

### **Severity**
Medium

### **Priority**
Medium

### **Type**
Bug

### **Assignee**
Jovolynn

**Comment by jovojynn** [comment]
updated the website! should be complete
