### ISSUE TITLE
 Homepage slider nav dots

### ISSUE THREAD

**Issue by RTang001** [jovojynn/qa-term-project#7]
Description:
After opening the home page, when scrolling down to the User recommendation section, the top slider image nav dots are overlapping  with the section. 
Upon testing, the slider works perfectly, but the slider dots may need to adjust their positions.

Steps to Reproduce:
1. Visit https://wanderlust.maijomade.com/
2. Scroll down to slider section (first section) 

Expected Result:
The slider nav dots should be display at the bottom of the slider image, above the user recommendation section.
<img width="306" alt="Screen Shot 2022-12-04 at 1 27 30 PM" src="https://user-images.githubusercontent.com/74392298/205516593-2453e5c6-8102-4c4f-90a7-4c7912508b51.png">

Actual Result:
The dots overlap with the user recommendation section images. The dots are hard to see.
<img width="306" alt="Screen Shot 2022-12-04 at 12 37 31 PM" src="https://user-images.githubusercontent.com/74392298/205516615-c2c7e05e-f6c1-45ae-994b-92b4bda0189b.png">

Configuration: 
This bug was found on the following configurations labeled in red.
<img width="306" alt="Screen Shot 2022-12-04 at 1 28 37 PM" src="https://user-images.githubusercontent.com/74392298/205516631-4c4e9daf-c762-4e86-9023-df9eda42d32e.png">

Severity: Medium  Priority: Medium

**Comment by jovojynn** [comment]
On my screen, it looks to be fixed! I need someone to test it out on a bigger screen.
